export const PredefinedBios = [
  "Living life to the fullest",
  "🍹 Cocktail lover | 🍸 Mixologist in training | 🍻 Beer aficionado",
  "Coding my dreams",
  "Tech enthusiast",
  "Lifelong learner",
  "Smile – you’ve made it.",
  "🌻 Sunflower enthusiast | 📚 Book lover | ☕ Coffee addict",
  "Explorer of the digital world",
  "Within every person is a sun.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "📚 Bibliophile | 📖 Book nerd | 🕯️ Candlelight reader",
  "Under construction.",
  "I am the reason I smile daily. ",
  "Happiness is a choice, and I choose it every day.",
  "I may want you but express it I will not.",
  "I am okay with losing people who are okay with losing me.",
  "👥Peeth Piche Kaun Kya Bolta Hai😇 Koi Farak Nahi Padta❌ Samne Kisi Ka Muh Nahi🗣️Khulta Kaafi Hai🔥",
  "Do not stress-everything is temporary.",
  "Sometimes all that works is a smile.",
  "🏋️‍♀️ Fitness fanatic | 🍎 Healthy living | 💪 Stronger every day",
];
